# Generated by Django 2.2.26 on 2022-03-08 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=45)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('photo', models.ImageField(blank=True, upload_to='profile_images')),
                ('bio', models.CharField(max_length=254)),
                ('gender', models.CharField(choices=[('0', ''), ('1', 'Male'), ('2', 'Female'), ('3', 'Prefer not to specify')], default=None, max_length=30)),
                ('sexualPreference', models.CharField(choices=[('0', ''), ('1', 'Male'), ('2', 'Female')], default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.IntegerField()),
                ('answer2', models.IntegerField()),
                ('answer3', models.IntegerField()),
                ('answer4', models.IntegerField()),
                ('answer5', models.IntegerField()),
                ('answer6', models.IntegerField()),
                ('answer7', models.IntegerField()),
                ('answer8', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TwosComplement.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibilityScore', models.IntegerField()),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='TwosComplement.UserProfile')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='TwosComplement.UserProfile')),
            ],
        ),
    ]
