# Generated by Django 2.2.26 on 2022-03-09 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('photo', models.ImageField(blank=True, upload_to='profile_images')),
                ('bio', models.CharField(max_length=254)),
                ('gender', models.CharField(choices=[('0', ''), ('1', 'Male'), ('2', 'Female'), ('3', 'Prefer not to specify')], default=None, max_length=30)),
                ('sexualPreference', models.CharField(choices=[('0', ''), ('1', 'Male'), ('2', 'Female'), ('3', 'No preference')], default=None, max_length=30)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.CharField(choices=[('0', ''), ('1', 'Python'), ('2', 'java'), ('3', 'C and related'), ('4', 'other')], default=None, max_length=30)),
                ('Q2', models.CharField(choices=[('0', ''), ('1', 'VSCode'), ('2', 'Eclipse'), ('3', 'IntelliJ'), ('4', 'PyCharm')], default=None, max_length=30)),
                ('Q3', models.CharField(choices=[('0', ''), ('1', '< 1 year'), ('2', '1-3 years'), ('3', '3-5 years'), ('4', '5+ years')], default=None, max_length=30)),
                ('Q4', models.CharField(choices=[('0', ''), ('1', 'Apps'), ('2', 'Databases'), ('3', 'Games'), ('4', 'Security')], default=None, max_length=30)),
                ('Q5', models.CharField(choices=[('0', ''), ('1', 'Artifical Intelligence'), ('2', 'Graphics'), ('3', 'Database Management Systems'), ('4', 'Human-Computer Interaction(HCI)')], default=None, max_length=30)),
                ('Q6', models.CharField(choices=[('0', ''), ('1', 'Capricorn'), ('2', 'Aquarius'), ('3', 'Pisces'), ('4', 'Aries'), ('5', 'Taurus'), ('6', 'Gemimi'), ('7', 'Cancer'), ('8', 'Leo'), ('9', 'Virgo'), ('10', 'Libra'), ('11', 'Scorpio'), ('12', 'Sagittarius')], default=None, max_length=30)),
                ('Q7', models.CharField(choices=[('0', ''), ('1', 'Extrovert'), ('2', 'Ambivert'), ('3', 'Introvert')], default=None, max_length=30)),
                ('Q8', models.CharField(choices=[('0', ''), ('1', 'Physical Touch'), ('2', 'Word of Affirmation'), ('3', 'Quality Time'), ('4', 'Gift Giving'), ('5', 'Acts of Service')], default=None, max_length=30)),
                ('Q9', models.CharField(choices=[('0', ''), ('1', 'Sports'), ('2', 'Travel'), ('3', 'Working'), ('4', 'Sleeping'), ('5', 'Clubbing'), ('6', 'TV/Movies'), ('7', 'Cooking'), ('8', 'Chilling')], default=None, max_length=30)),
                ('Q10', models.CharField(choices=[('0', ''), ('1', 'Italian'), ('2', 'Indian'), ('3', 'Chinese'), ('4', 'Mexican'), ('5', 'other'), ('6', 'No Preference')], default=None, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibilityScore', models.IntegerField()),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='TwosComplement.UserProfile')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='TwosComplement.UserProfile')),
            ],
        ),
    ]
