# Generated by Django 2.2.26 on 2022-03-09 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TwosComplement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matches',
            options={'verbose_name_plural': 'Matches'},
        ),
    ]
