# Generated by Django 2.2.26 on 2022-03-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwosComplement', '0002_auto_20220308_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='answer10',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='answer4',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='answer5',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='answer6',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='answer7',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='answer8',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='answer9',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='Q1',
            field=models.CharField(choices=[('0', ''), ('1', 'Python'), ('2', 'java'), ('3', 'C and related'), ('4', 'other')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='Q10',
            field=models.CharField(choices=[('0', ''), ('1', 'Italian'), ('2', 'Indian'), ('3', 'Chinese'), ('4', 'Mexican'), ('5', 'other'), ('6', 'No Preference')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='Q2',
            field=models.CharField(choices=[('0', ''), ('1', 'VSCode'), ('2', 'Eclipse'), ('3', 'IntelliJ'), ('4', 'PyCharm')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='Q3',
            field=models.CharField(choices=[('0', ''), ('1', '< 1 year'), ('2', '1-3 years'), ('3', '3-5 years'), ('4', '5+ years')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='Q4',
            field=models.CharField(choices=[('0', ''), ('1', 'Apps'), ('2', 'Databases'), ('3', 'Games'), ('4', 'Security')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='Q5',
            field=models.CharField(choices=[('0', ''), ('1', 'Artifical Intelligence'), ('2', 'Graphics'), ('3', 'Database Management Systems'), ('4', 'Human-Computer Interaction(HCI)')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='Q6',
            field=models.CharField(choices=[('0', ''), ('1', 'Capricorn'), ('2', 'Aquarius'), ('3', 'Pisces'), ('4', 'Aries'), ('5', 'Taurus'), ('6', 'Gemimi'), ('7', 'Cancer'), ('8', 'Leo'), ('9', 'Virgo'), ('10', 'Libra'), ('11', 'Scorpio'), ('12', 'Sagittarius')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='Q7',
            field=models.CharField(choices=[('0', ''), ('1', 'Extrovert'), ('2', 'Ambivert'), ('3', 'Introvert')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='Q8',
            field=models.CharField(choices=[('0', ''), ('1', 'Physical Touch'), ('2', 'Word of Affirmation'), ('3', 'Quality Time'), ('4', 'Gift Giving'), ('5', 'Acts of Service')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='Q9',
            field=models.CharField(choices=[('0', ''), ('1', 'Sports'), ('2', 'Travel'), ('3', 'Working'), ('4', 'Sleeping'), ('5', 'Clubbing'), ('6', 'TV/Movies'), ('7', 'Cooking'), ('8', 'Chilling')], default=None, max_length=30),
        ),
    ]
